### ISSUE TITLE
THis is not a v.3.x Version

### ISSUE THREAD

**Issue by IP-CAM** [E-ComProcessing/opencart-ecp-plugin#4]
It uses x.tpl Files in the Theme Sections, and it's therefore not capable to be used in OC v.3.x Versions

**Comment by dyd** [comment]
@IP-CAM did you try the plugin or is your comment based only on the files' review? The plugin uses its own template engine.

**Comment by IP-CAM** [comment]
Opencart v.3.x does not use x.**tpl**-files in it's Theme Sections.
